dist: xenial
language: node_js
node_js:
  - node
  - 'lts/*'
services:
  - docker
script:
  - yarn lint
  - make test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true