version: '3.5'
services:
  test:
    build:
      context: .
    command: sh -c "/wait && yarn test"
    tty: true
    environment:
      HOST: arangodb
      WAIT_HOSTS: arangodb:8529
      WAIT_AFTER_HOSTS: 5
    volumes:
      - .:/app

  arangodb:
    image: arangodb
    environment:
      ARANGO_NO_AUTH: 1
    ports:
      - 8529:8529
